# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b113b03a19ee7972146a181c34d0fc2a0317d8ab1b7061aef0faea34539f99ffb155dd65c9ac2a4327cae38dd5d1045fb2a7f11bf3709905b2e119e335eb61a

test:
  secret_key_base: 71dcc5a93f03697af20a1286927cadceb56220b4db274f5eaa173fd6c356e34deef5e76d403a6a3d93e378866651bd4688f9856224d4d17108213dfb1671df02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
